name: know_clock
description: Triad Factory know_clock app.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # package
  common:
    path: package/common
  domain:
    path: package/domain
  presentation:
    path: package/presentation
  source_local:
    path: package/source_local
  ui:
    path: package/ui
  # flutter
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
